### ISSUE TITLE
Posted to Opendata.ch/2024 showcase

### ISSUE THREAD

**Issue by loleg** [binghamchris/paddelbuch#79]
Thanks a lot for dropping a link to your project at the annual Forum! I've posted this repo to our online Showcase as well. Please feel free to Join and Edit to your liking: https://showcase.opendata.ch/project/63

:tada: Did you know, today is the 10th anniversary of the [International Open Data Hackdays](http://make.opendata.ch/wiki/event:2014-5)? Let's think about opportunities to connect your work to future hackathons and activities in our communities.

If you have any other questions, let me know.

**Comment by binghamchris** [comment]
Thanks Oleg, however could you remove my personal profile picture from your site please?

I ask for this for 2 reasons:

1. A portion of the Paddel Buch data was provided by various other people, so I feel that having my face being the photo for the project is not representative of the contributors.
2. I notice that your site's footer says everything on it is CC-BY 4.0 licensed. My personal profile photo is very much "copyright me, all rights reserved"! ;) 

Instead I'd suggest using the Paddel Buch's [favicon](https://github.com/binghamchris/paddelbuch/blob/main/src/assets/images/logo-favicon.svg) or a screenshot of the site from www.paddelbuch.ch.

**Comment by loleg** [comment]
Chris, hi, thanks for getting in touch - sorry I did not get a notification of your reply. In fact, your picture was placed there automatically, because it is associated with the GitHub repository under your personal account. I have edited the [Showcase page](https://showcase.opendata.ch/project/63), and put a screenshot as you requested.

It is free and relatively easy to move to a GitHub Organization, and given your remarks, I would suggest you do this. [@OpendataCH](https://github.com/OpendataCH/) also hosts a few community projects, if you think this would be a good option. If we had a Sports working group, this is where we would actively try to host or fork [open sports data sources](https://datahub.io/organization/sport) and projects like yours.

**Comment by binghamchris** [comment]
Thanks for updating the page Oleg, and your suggestions.

FYI the data itself is not contained in GitHub. Rather it's maintained in a CMS (which is not public, for security) and is published via a static API on the paddelbuch.ch website. This repo only contains the code for building the website and API.
